version: '3.8'

services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: shelfswap
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./ShelfSwap
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    volumes:
      - ./ShelfSwap/uploads:/app/public/uploads
    environment:
      - PORT=5000
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASS=123456
      - DB_NAME=shelfswap

volumes:
  mysql_data:
